### ISSUE TITLE
DateTimeParseException for unknown reason

### ISSUE THREAD

**Issue by srikrishnacj** [gkopff/gson-javatime-serialisers#16]
java.time.format.DateTimeParseException: Text '' could not be parsed at index 0
	at java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:1947)
	at java.time.format.DateTimeFormatter.parse(DateTimeFormatter.java:1849)
	at com.fatboyindustrial.gsonjavatime.LocalTimeConverter.deserialize(LocalTimeConverter.java:95)
	at com.fatboyindustrial.gsonjavatime.LocalTimeConverter.deserialize(LocalTimeConverter.java:1)
	at com.google.gson.TreeTypeAdapter.read(TreeTypeAdapter.java:58)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:103)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:196)
	at com.google.gson.Gson.fromJson(Gson.java:810)
	at com.google.gson.Gson.fromJson(Gson.java:775)
	at com.google.gson.Gson.fromJson(Gson.java:724)
	at com.google.gson.Gson.fromJson(Gson.java:696)
	at xxx.util.JsonUtil.fromJson(JsonUtil.java:19)
	at xxx.servlet.yyy.zzzServlet.doGet(CreateSchedule.java:38)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:622)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:291)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.logging.log4j.web.Log4jServletFilter.doFilter(Log4jServletFilter.java:71)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:219)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:617)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518)
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091)
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:668)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1521)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1478)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

I am continuously getting the above the error. but i am failed to find the exact cause. i have downloaded the source and attached it to my application. when i debug it, i found the exception is being thrown when LocalTime is formated from empty string

**Comment by mwanji** [comment]
> when i debug it, i found the exception is being thrown when LocalTime is formated from empty string

Doesn't this indicate that the string you're passing in is an invalid LocalTime?

**Comment by gkopff** [comment]
The code as it currently is expects that the time format be a valid format.  This definitely will be the case if it was also this code that serialised the JSON in the first place.  If the time string originates elsewhere, it's (currently) up to you to ensure it's valid before attempting to deserialise.

I use the library to round-trip data between services that are homogeneous - so that's the only use case I have firm opinions about.

An obvious alternative behaviour to throwing the `DateTimeParseException` would be to have any format exception deserialise to `null`.  The upside of this is that a single error won't bring down the whole document parse.  The downside is that bad data is silently converted to `null`, and you'll only discover the `null` later on down the track.  Silently converting to null on bad data doesn't sit well with me.

However, a middle ground also exists - an *empty string* could be made to explicitly deserialise to `null`.

Thoughts?

**Comment by srikrishnacj** [comment]
Never i error got cleared itself. but it is still mysterious for me how that error is raised. 
@mwanji : i think GSON throws empty JSONElement if class field is not present in json string. thats why my localtime is being passed as empty string to converter.

**Comment by mwanji** [comment]
@srikrishnacj Can you give the json that produces the exception?
